FROM golang:1.10.1 AS builder
RUN go version

COPY . /go/src/testing/
WORKDIR /go/src/testing/

RUN  go get gopkg.in/mgo.v2/bson
RUN  go get github.com/salihkemaloglu/UnitAndIntegrationTesting-Golang/operations

EXPOSE 8081
ENTRYPOINT ["go","test","-v"]